author: "Faysal Ahmed(forked) <kawsar.ahmed042@gmail.com>"
category: "offline"
summary: "Forwards messages that are sent to offline users through a post request to a configurable url(parse server)"
home: "https://github.com/faysal515/mod_offline_post/tree/master/"
url: "git@github.com:faysal/mod_offline_post.git"
